{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintJavalette where

-- pretty-printer generated by the BNF converter

import AbsJavalette
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
   PProg defs -> prPrec i 0 (concatD [prt 0 defs])


instance Print Def where
  prt i e = case e of
   FnDef type' id args block -> prPrec i 0 (concatD [prt 0 type' , prt 0 id , doc (showString "(") , prt 0 args , doc (showString ")") , prt 0 block])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Arg where
  prt i e = case e of
   DArg type' id -> prPrec i 0 (concatD [prt 0 type' , prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Block where
  prt i e = case e of
   DBlock stms -> prPrec i 0 (concatD [doc (showString "{") , prt 0 stms , doc (showString "}")])


instance Print Stm where
  prt i e = case e of
   SEmpty  -> prPrec i 0 (concatD [doc (showString ";")])
   SBlock block -> prPrec i 0 (concatD [prt 0 block])
   SDecl type' items -> prPrec i 0 (concatD [prt 0 type' , prt 0 items , doc (showString ";")])
   SAss id exp -> prPrec i 0 (concatD [prt 0 id , doc (showString "=") , prt 0 exp , doc (showString ";")])
   SIncr id -> prPrec i 0 (concatD [prt 0 id , doc (showString "++") , doc (showString ";")])
   SDecr id -> prPrec i 0 (concatD [prt 0 id , doc (showString "--") , doc (showString ";")])
   SRet exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp , doc (showString ";")])
   SVRet  -> prPrec i 0 (concatD [doc (showString "return") , doc (showString ";")])
   SIf exp stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SIfElse exp stm0 stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm0 , doc (showString "else") , prt 0 stm])
   SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SExp exp -> prPrec i 0 (concatD [prt 0 exp , doc (showString ";")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Item where
  prt i e = case e of
   IDecl id -> prPrec i 0 (concatD [prt 0 id])
   IInit id exp -> prPrec i 0 (concatD [prt 0 id , doc (showString "=") , prt 0 exp])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Type where
  prt i e = case e of
   TInt  -> prPrec i 0 (concatD [doc (showString "int")])
   TDoub  -> prPrec i 0 (concatD [doc (showString "double")])
   TBool  -> prPrec i 0 (concatD [doc (showString "boolean")])
   TVoid  -> prPrec i 0 (concatD [doc (showString "void")])
   TFun type' types -> prPrec i 0 (concatD [prt 0 type' , doc (showString "(") , prt 0 types , doc (showString ")")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Exp where
  prt i e = case e of
   EVar id -> prPrec i 6 (concatD [prt 0 id])
   ELit lit -> prPrec i 6 (concatD [prt 0 lit])
   EApp id exps -> prPrec i 6 (concatD [prt 0 id , doc (showString "(") , prt 0 exps , doc (showString ")")])
   EString str -> prPrec i 6 (concatD [prt 0 str])
   ENeg exp -> prPrec i 5 (concatD [doc (showString "-") , prt 6 exp])
   ENot exp -> prPrec i 5 (concatD [doc (showString "!") , prt 6 exp])
   EMul exp0 mulop exp -> prPrec i 4 (concatD [prt 4 exp0 , prt 0 mulop , prt 5 exp])
   EAdd exp0 addop exp -> prPrec i 3 (concatD [prt 3 exp0 , prt 0 addop , prt 4 exp])
   ERel exp0 relop exp -> prPrec i 2 (concatD [prt 2 exp0 , prt 0 relop , prt 3 exp])
   EAnd exp0 exp -> prPrec i 1 (concatD [prt 2 exp0 , doc (showString "&&") , prt 1 exp])
   EOr exp0 exp -> prPrec i 0 (concatD [prt 1 exp0 , doc (showString "||") , prt 0 exp])
   EType type' exp -> prPrec i 0 (concatD [prt 0 type' , prt 0 exp])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Lit where
  prt i e = case e of
   LInt n -> prPrec i 0 (concatD [prt 0 n])
   LDoub d -> prPrec i 0 (concatD [prt 0 d])
   LTrue  -> prPrec i 0 (concatD [doc (showString "true")])
   LFalse  -> prPrec i 0 (concatD [doc (showString "false")])


instance Print AddOp where
  prt i e = case e of
   Plus  -> prPrec i 0 (concatD [doc (showString "+")])
   Minus  -> prPrec i 0 (concatD [doc (showString "-")])


instance Print MulOp where
  prt i e = case e of
   Times  -> prPrec i 0 (concatD [doc (showString "*")])
   Div  -> prPrec i 0 (concatD [doc (showString "/")])
   Mod  -> prPrec i 0 (concatD [doc (showString "%")])


instance Print RelOp where
  prt i e = case e of
   Lt  -> prPrec i 0 (concatD [doc (showString "<")])
   LtEq  -> prPrec i 0 (concatD [doc (showString "<=")])
   Gt  -> prPrec i 0 (concatD [doc (showString ">")])
   GtEq  -> prPrec i 0 (concatD [doc (showString ">=")])
   Eq  -> prPrec i 0 (concatD [doc (showString "==")])
   NEq  -> prPrec i 0 (concatD [doc (showString "!=")])



