#!/bin/bash
#rm main.*
rm test.ll
#rm a.out

exec ./src/Main "$@" | llvm-as test.ll        # call Main and then compile test.ll

llvm-link test.bc ./lib/runtime.bc -o main.bc # link with runtime to create main.bc
llc -filetype=obj main.bc                     # create .o file
gcc main.o                                    # produce executable file a.out

cat test.ll
