#!/bin/bash
cd src
make
cd ..
rm main.bc
rm main.o
rm a.out

#./jlc test.jl

./jlc graderTestSuite/good/core001.jl

# llvm-as tester/testsuite/good/core030.ll
# llvm-link tester/testsuite/good/core030.bc lib/runtime.bc -o main.bc
# llc -filetype=obj main.bc
# gcc main.o
# ./a.out
# echo ""
# cat tester/testsuite/good/core030.output
# echo "----------------------------------------"
